---
# included file

- name: Jenkins Java Cmd
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_JAVA_CMD=
    line: 'JENKINS_JAVA_CMD="{{ jenkins2_java_cmd }}"'
  become: yes
  notify:
    - Restart Jenkins

- name: Jenkins Java Options
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_JAVA_OPTIONS=
    line: 'JENKINS_JAVA_OPTIONS="{{ jenkins2_java_options }}"'
  become: yes
  notify:
    - Restart Jenkins

- name: Jenkins Port
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_PORT=
    line: 'JENKINS_PORT={{ jenkins2_http_port }}'
  become: yes
  notify:
    - Restart Jenkins

- name: Jenkins Listen Address
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_LISTEN_ADDRESS=
    line: 'JENKINS_LISTEN_ADDRESS="{{ jenkins2_listen_address }}"'
  become: yes
  notify:
    - Restart Jenkins

- name: Jenkins Debug Level
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_DEBUG_LEVEL=
    line: 'JENKINS_DEBUG_LEVEL={{ jenkins2_debug_level }}'
  become: yes
  notify:
    - Restart Jenkins

- name: Jenkins Enable Access Log
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_ENABLE_ACCESS_LOG=
    line: 'JENKINS_ENABLE_ACCESS_LOG="{{ jenkins2_enable_access_log }}"'
  become: yes
  notify:
    - Restart Jenkins

- name: Jenkins Handler Max
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_HANDLER_MAX=
    line: 'JENKINS_HANDLER_MAX={{ jenkins2_handler_max }}'
  become: yes
  notify:
    - Restart Jenkins

- name: Jenkins Handler Idle
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_HANDLER_IDLE=
    line: 'JENKINS_HANDLER_IDLE={{ jenkins2_handler_idle }}'
  become: yes
  notify:
    - Restart Jenkins

- name: Jenkins Args
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_ARGS=
    line: 'JENKINS_ARGS="{{ jenkins2_args }}"'
  become: yes
  notify:
    - Restart Jenkins

- meta: flush_handlers
