---


- name: Eliminar nodos config Gitlab
  xml:
    path: "{{ jenkins2_home }}/com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig.xml"
    xpath: /com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig/connections/com.dabsquared.gitlabjenkins.connection.GitLabConnection/clientBuilder
    state: absent
  
- name: Añadir tokenid config gitlab
  xml:
    path: "{{ jenkins2_home }}/com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig.xml"
    xpath: /com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig/connections/com.dabsquared.gitlabjenkins.connection.GitLabConnection/apiTokenId
    value: "{{ gitlab['site']['tokenid'] }}"

- name: Añadir nombre config gitlab
  xml:
    path: "{{ jenkins2_home }}/com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig.xml"
    xpath: /com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig/connections/com.dabsquared.gitlabjenkins.connection.GitLabConnection/name
    value: "{{ gitlab['site']['name'] }}"

- name: Añadir url config gitlab
  xml:
    path: "{{ jenkins2_home }}/com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig.xml"
    xpath: /com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig/connections/com.dabsquared.gitlabjenkins.connection.GitLabConnection/url
    value: "{{ gitlab['site']['url'] }}"

- name: Ignorar errores certificados gitlab
  xml:
    path: "{{ jenkins2_home }}/com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig.xml"
    xpath: /com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig/connections/com.dabsquared.gitlabjenkins.connection.GitLabConnection/ignoreCertificateErrors
    value: "{{ gitlab.site.certificate.errors }}"

- name: config trigger gitlab
  xml:
    path: "{{ jenkins2_home }}/com.dabsquared.gitlabjenkins.GitLabPushTrigger.xml"
    xpath: /com.dabsquared.gitlabjenkins.GitLabPushTrigger_-DescriptorImpl/ignoreCertificateErrors
    value: "{{ gitlab.site.certificate.errors }}"

- name: config paquete Git
  xml:
    path: "{{ jenkins2_home }}/hudson.plugins.git.GitTool.xml"
    xpath: /hudson.plugins.git.GitTool_-DescriptorImpl/installations/hudson.plugins.git.GitTool/name
    value: 'GIT'


- name: config paquete Git
  xml:
    path: "{{ jenkins2_home }}/hudson.plugins.git.GitTool.xml"
    xpath: /hudson.plugins.git.GitTool_-DescriptorImpl/installations/hudson.plugins.git.GitTool/home
    value: '/usr/bin/git'
