---
# included file

- name: Jenkins CLI
  get_url:
    url: "http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path | default('') }}/jnlpJars/jenkins-cli.jar"
    dest: /tmp/jenkins-cli.jar
    owner: root
    group: root
    mode: 0444

- name: Scripts for Jenkins CLI
  template:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
    owner: root
    group: root
    mode: 0444
  with_items:
    - security_realm_name.sh
    - proxy_configuration.groovy
    - update_center_refresh.groovy

- name: Security Realm Checking
  shell: "bash /tmp/security_realm_name.sh"
  register: jenkins2_security_realm_name

- name: CLI Password File Creation
  copy:
    content: "{{ jenkins2_cli_username }}:{{ jenkins2_cli_password }}"
    dest: /tmp/jenkins-cli-credentials
    mode: 0400
  when: jenkins2_security_realm_name.stdout != "hudson.security.SecurityRealm$None"

- name: Proxy Configuration
  shell: "cat /tmp/proxy_configuration.groovy | java -jar /tmp/jenkins-cli.jar -s http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path | default('') }}{% if jenkins2_security_realm_name.stdout != 'hudson.security.SecurityRealm$None' %} -auth @/tmp/jenkins-cli-credentials{% endif %} groovy ="

- name: Update Center Refresh
  shell: "cat /tmp/update_center_refresh.groovy | java -jar /tmp/jenkins-cli.jar -s http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path | default('') }}{% if jenkins2_security_realm_name.stdout != 'hudson.security.SecurityRealm$None' %} -auth @/tmp/jenkins-cli-credentials{% endif %} groovy ="

- name: Plugins Installation
  shell: "java -jar /tmp/jenkins-cli.jar -s http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path | default('') }}{% if jenkins2_security_realm_name.stdout != 'hudson.security.SecurityRealm$None' %} -auth @/tmp/jenkins-cli-credentials{% endif %} install-plugin {{ item }}"
  with_items:
    - "{{ jenkins2_suggested_plugins }}"
    - "{{ jenkins2_plugins }}"
  notify:
    - Restart Jenkins

- name: CLI Password File Deletion
  file:
    path: /tmp/jenkins-cli-credentials
    state: absent
