---
# handlers file for ansible-role-jenkins

# https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/jenkins/install/platform-plugins.json

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted
  notify: Wait for Jenkins
  become: yes

- name: Wait for Jenkins
  uri:
    url: "http://localhost:{{ jenkins2_http_port }}{{ jenkins2_context_path | default('') }}/login"
    status_code: 200
  register: jenkins2_login_page
  until: jenkins2_login_page.status == 200
  retries: 60
  delay: 1
